### ISSUE TITLE
Redundant naming

### ISSUE THREAD

**Issue by mhuggins** [TamerShlash/symbolized#1]
Not an "issue" per se, but it seems redundant for the class name to be `Symbolized::SymbolizedHash`.  Why not just `Symbolized::Hash`?

**Comment by mhuggins** [comment]
Feel free to just close this, thought I'd ask though. :)

**Comment by TamerShlash** [comment]
Imagine if we try to name it `Symbolized::Hash`, the class definition would look like:

```
module Symbolized
  class Hash < Hash
  end
end
```

Not so nice, right? :wink: 

Even though that seems technically possible, I wouldn't confuse the native `Hash` class with the class this gem provides. And forcing people to add namespace all the time is not a nice idea. I already added `SymbolizedHash = Symbolized::SymbolizedHash` after the class definition, to export the class to the global namespace for easier use.

**Comment by mhuggins** [comment]
This is easily fixed by denoting that the parent class is the ruby core `Hash` via the double-colon syntax. :)

``` ruby
module Symbolized
  class Hash < ::Hash
  end
end
```

**Comment by mhuggins** [comment]
I didn't realize that you made it a top-level class name though.
