### ISSUE TITLE
This doesn't seem to be more efficient than using string keys

### ISSUE THREAD

**Issue by jakeonrails** [TamerShlash/symbolized#2]
Given the following benchmark script, using the OS gem for the `#rss_bytes` method:

``` ruby
#!/usr/env/bin ruby

require 'os'

def mem_usage(name, &block)
  start = OS.rss_bytes
  yield
  finish = OS.rss_bytes
  puts "#{name} uses #{(finish - start) / 1024}mb"
end

mem_usage("to_sym") { 1_000_000.times.inject({}) { |h, n| h[n.to_s.to_sym] = n; h } }

mem_usage("to_s") { 1_000_000.times.inject({}) { |h, n| h[n.to_s] = n; h} }

mem_usage("to_i") { 1_000_000.times.inject({}) { |h, n| h[n.to_i] = n; h } }

```

I get the following output:

```
to_sym uses 327mb
to_s uses 144mb
to_i uses 48mb
```

So it would seem that using symbolic keys is actually more memory consuming than strings or ints. I think this is because Ruby keeps symbols around in a separate place in memory so that it can maintain a mapping between the string version of a symbol and the integer/numeric/whatever internal representation Ruby uses to simplify them.

Am I missing something here?

(Using ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13])

**Comment by ihavecoke** [comment]
i think this gem fit some one who just like use hash key in  symbol.

**Comment by TamerShlash** [comment]
This is interesting. Although the benchmark is not so dependable, I did some variations and still got some interesting results. I'll dig deeper into Ruby's internal implementation of Strings and Symbols (because there seems to be some connection internally) and see if this gem is of any use after that.
